server:
  port: 8082
spring:
  config:
    import: optional:configserver:http:${PITAM_CONFIG_SERVER_URI:http://localhost:8888/pitamconfigserver}
eureka:
  client:
    service-url:
      defaultZone: ${PITAM_EURECA_SERVER_URI:http://localhost:8761/eureka}
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

